#!/usr/bin/env bash
# Displays while, if , elif, else (for and until are forbidden)

#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

count=0

while [ $count -lt 10 ];
do
  
  if [ $count -eq 3 ];
      echo "Bad luck"
  then
  elif [ $count -eq 7 ]; 
      echo "Good luck"
  then
  else
      echo "Best School"
  fi
      ((count++))
done
