#!/usr/bin/env bash
#Displays numbers from 1 to 20

#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration
#While & Case

count=0

while [ $count -lt 20 ];
do
  case $count in
    3)
      echo "bad luck from China"
    ;;    
    8)
      echo "bad luck from Japan"
    ;;    
    16)
      echo "bad luck from Italy"
    ;;
    *)
      echo "default"
    ;;
  esac
    ((count++))
done
