#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes

#display hours from 0 to 12
#display minutes from 1 to 59
#while 
#display the first 70 lines using the head command

hour=0
minute=1

while [ $hour -le 12 ];
do
    echo "$hours"
while [ $minute -le 59 ];
do
    echo "$minutes"
    ((hour++))
    ((minute++))
done
