#!/usr/bin/env bash
#localhost resolves to 127.0.0.2 & facebook.com resolves to 8.8.8.8

if grep -qxF "127.0.0.2 localhost" /etc/hosts;
then
    echo "localhost already resolves to 127.0.0.2"
else
    echo "127.0.0.2 localhost" >> /etc/hosts
fi

if grep -qxF "8.8.8.8 facebook.com" /etc/hosts;
then
    echo "facebook.com already resolves to 8.8.8.8"
else
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
