#!/usr/bin/env bash
#localhost resolves to 127.0.0.2 & facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
if ! grep -qE '127\.0\.0\.2\s+localhost' ~/hosts.new; 
then
    echo '127.0.0.2 localhost' >> ~/hosts.new
fi
if ! grep -qE '8\.8\.8\.8\s+facebook\.com' ~/hosts.new; 
then
    echo '8.8.8.8 facebook.com' >> ~/hosts.new
fi
cp -f ~/hosts.new /etc/hosts
