#!/usr/bin/env bash
#localhost resolves to 127.0.0.2 & facebook.com resolves to 8.8.8.8

sudo sed -i 's/^127\.0\.0\.1.*$/127.0.0.2 localhost/' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts
echo '8.8.8.8 facebook.com' | sudo tee -a

sudo systemctl restart systemd-resolved

